name: stx_list_extensions
description: Provides useful list extensions
version: 1.0.0

repository: https://github.com/StepanchukPv/stx_list_extensions
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
