name: CI test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dart@v2.18.2

      - run: dart pub get
      - run: dart analyze
      - run: dart test
